CSRF_ENABLED = True
DROP_ALL = False

WEIXIN_TOKEN = 'whosyourdaddy'
WEIXIN_ENCODINGAESKEY = '1jp8P13SBoh0BSixJqDycBzFTDPHcKKkuFcQCDprHCz'
WEIXIN_APPID = 'wx6c954bca5edf9e7a'

SECRET_KEY = 'you-will-never-guess'
UPLOAD_THEME = '/var/www/FlaskApp/FlaskApp/static/images/upload_theme'
SQLALCHEMY_DATABASE_URI = ''
SQLALCHEMY_POOL_SIZE = 50
SQLALCHEMY_POOL_TIMEOUT = 10
SQLALCHEMY_TRACK_MODIFICATIONS = True
WHOOSH_BASE = 'searchindex'
MAX_SEARCH_RESULTS = 20